version: '3.8'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_PORT=6379
  voterapi:
    image: voterapi:latest
    container_name: voterapi
    restart: always
    environment:
      - REDIS_URL=cache:6379
    ports:
      - 8080:8080
    depends_on:
      - cache